allowBuilds:
  esbuild: true

registries:
  default: https://registry.npmjs.org/
  "@j4k": https://code.j4k.dev/api/packages/j4k/npm/
enableGlobalVirtualStore: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - "@j4k/*"
